### ISSUE TITLE
USB Serial Port not shown

### ISSUE THREAD

**Issue by eyuan-creare** [Tympan/Tympan_Rev_F_Hardware#12]
There is no serial USB port shown in the Arduino IDE.  This has occurred on hardware S/N TYM-F003(@eyuan-creare) and F004 (@cab-creare-com).  

Regarding TYM-F003
-  Switching computers did not work. 
- Uploading a simple blink sketch (via compile and upload in the IDE, or via teensy loader directly).
- Bluetooth light would turn off, then turn on again, as if it was power cycling.
- Occurred after being fully charged.
- Was eventually resolved (much later) after pressing the program button (even though no serial port was shown).

Regarding TYM-F004
- Prior to the issue, was working correctly for several weeks.

**Comment by eyuan-creare** [comment]
@cab-creare-com I'll try out your Tympan tomorrow and can give you a new one if you need it. Can you document the circumstances, since this is the second time this has occurred?  Arduino IDE version, sketch uploaded last, Tympan library branch, battery charged (i imagine you leave it connected).  Did you try pressing the program button? etc...

@chipaudette Anything to add about what you experienced with the Tympan that was giving me issues?

Might be worth comparing the Rev-E and -F PCB to see if there is anything about the Teensy boot process that is different.  I was surprised my Tympan TYM-F003 started working again after stubbornly resisting everything I tried.

**Comment by chipaudette** [comment]
I've been suspicious of the coin cell battery as a potential source of bizarre system behavior.  What happens when the coin cell gets really dead?  Will the system work OK?  Would it be better to have no coin cell at all?

In the unit that I debugged for @eyuan-creare, I pulled the coin cell and did not replace it.  The Tympan started working shortly after that (also after a long press of the reset button).  Maybe removing the coin cell helped? Maybe it was irrelevant?  I don't know.

I'd like to see if the coin cell is relevant, if you're willing.  If you have this reprogramming problem again, can you document (1) whether a coin cell is present at all, and (2) what is the coin cell voltage (measured with a multimeter or whatever)?

**Comment by eyuan-creare** [comment]
### TYM-F004 Troubleshooting
A) Error on @eyuan-creare PC.  No lights except for charging LED.
> Teensy should be selected from "teensy ports" rather
> than "Serial ports" in Arduino's Tools > Port menu
> No Teensy boards were found on any USB ports of your computer.
> Please press the PROGRAM MODE BUTTON on your Teensy to upload your sketch. 
- Pressing program button had no effect.  No Teensy verbose message shown.
- There was no coin cell installed.  Installing brand new coin cell had no effect.

**Works when SD Card removed**
- I removed the SD Card in order to look at the bare board.  With it removed, I turned it on.  BT LED flashed and the USB Serial port showed up again.  I power cycled, and the USB Serial port showed correctly.  I did not try programming it.
- I reinserted the SD card and it exhibited the problem behavior - no LED (besides charging) and no USB Serial Port.

**Works with new SD Card**
SD Card was Sandisk Extreme A1 32GB
- When inserted in @eyuan-creare PC, the drive did not show up.
- Inserted a new SD Card (SanDisk Extreme Pro A2 128GB).  Tympan shows flashing BT LEDs and USB Serial port shows up in the Arduino IDE.

CASE CLOSED on TYM-F004 (ref @cab-creare-com, @chipaudette)
- Problem was corrupt SD Card.  Did not try to reformat the old card.  Left the new card in.

**Comment by biomurph** [comment]
@eyuan-creare 
Great work figuring that out! I hope that continues to be the root cause.

@chipaudette 
I am shipping Tympans without the coin battery installed. 
I do provide a coin cell, separate in the kit.
We had a discussion about how the Teensy 4.1 really drags the battery down fast, and so since we don’t need it, I include it as an option. The coin cell + is connected to the V-Bat pin on Teensy. It sounds like the internal RTC date and time is set according to the computer time on upload, and an optional battery on V-Bat will let Teensy keep time when powered down. This is from PJRC site:

> VBAT
> A 3 volt coin cell may be connected to VBAT & GND to allow the RTC to keep track of date / time while power is off. A CR2032 type battery is recommended, though other 3V coin cells may also be used.

**Comment by chipaudette** [comment]
@eyuan-creare, nice sleuthing!

@biomurph, thanks for the clarification on shipping without coin cell installed.  I agree with your stated procedure when delivering Tympans.  So far, it's only the dosimeter folks who have expressed any need for the RTC...so your plan for regular Tympans is a good one, IMO.

**Comment by eyuan-creare** [comment]
### TYM-F003 Issue back, but fixed it
Symptom: Only the LED for the BLE is lit, and it is slowly fading in and out.  No USB serial port listed in Arduino IDE
- Pressed the program button - no update on Teensy Loader
- Removed the coin cell, then pressed the program button - no update on Teensy Loader
- Replaced the coin cell with a brand new one. Pressed program button - no update on Teensy Loader
- Removed the battery. BLE LED started flashing.  Pressed program button but no update.  No USB serial port.
- 
THEN, swapped batteries.  No serial port listed.  Then I pressed the program button and a sketch was uploaded.  Serial port is now listed in Arduino IDE.
- Measured old battery at 2.5V.  Yikes!!! Looks like we need brownout protection.

Old battery swapped by (still low charge) and original problem behavior was observed.

**Comment by eyuan-creare** [comment]
Resolution: Swapping to a battery with more charge allowed firmware to be "manually" uploaded with the program button, even though the serial port was not listed.

**Comment by eyuan-creare** [comment]
Reminder to develop new enclosure for Tympan with integrated Teensy and optional shield.
